name: Build & Release

permissions:
  contents: write

on:
  push:
    branches: [main, layers]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install
      - name: Build Clones Quality Agent for All Operating Systems
        run: bun run build

      - name: Fix Artifact Permissions
        run: chmod -R +r target/

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          path: target/
          compression-level: 0

  release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # This is important for getting all tags

      - name: Get version from package.json
        id: get_version
        run: |
          version=$(jq -r .version package.json)
          echo "Version from package.json: $version"
          new_tag="v$version"
          echo "NEW_TAG=$new_tag" >> $GITHUB_ENV
          echo "Tag for release will be: $new_tag"

      - name: Delete existing release if it exists
        run: |
          if gh release view ${{ env.NEW_TAG }} &> /dev/null; then
            echo "Deleting existing release ${{ env.NEW_TAG }}"
            gh release delete ${{ env.NEW_TAG }} --yes --cleanup-tag
          else
            echo "No existing release found for ${{ env.NEW_TAG }}"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Display structure of downloaded files
        run: ls -R artifacts/

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.NEW_TAG }}
          name: Release ${{ env.NEW_TAG }}
          draft: false
          prerelease: false
          files: artifacts/artifact/*
          generate_release_notes: true
          fail_on_unmatched_files: false
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
