name: my-workflow

jobs:
  build:
    on:
      push:
        branches: [main]
      pr:
        branches: [main]
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      # install and run build
      - name: Install Dependencies
        run: bun install
      - name: Build Pipeline for All Operating Systems
        run: bun run build

  release:
    on:
      push:
        branches: [main]
    needs: [build]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Display structure of downloaded files
        run: ls -R artifacts/

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v0.0.1
          name: Release v0.0.1
          draft: false
          prerelease: false
          files: artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
